server.port=8081

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

app.consumer.threads=80
app.consumer.prefetch=10
app.consumer.concurrent-consumers-per-queue=1
app.consumer.max-retries=3
app.consumer.retry-track-max-size=50000
app.rabbitmq.queue-message-ttl=60000
app.rabbitmq.queue-max-length=1000

# Deduplication
app.dedup.cache-ttl-minutes=5
app.dedup.cache-max-size=50000

# DynamoDB
aws.dynamodb.endpoint-url=
aws.dynamodb.region=us-east-1
aws.dynamodb.access-key=
aws.dynamodb.secret-key=

app.dynamodb.table.messages=ChatMessages
app.dynamodb.table.user-activity=UserActivity
app.dynamodb.table.room-analytics=RoomAnalytics

# Circuit Breaker
resilience4j.circuitbreaker.instances.dynamodb-messages.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.dynamodb-messages.sliding-window-size=50
resilience4j.circuitbreaker.instances.dynamodb-messages.failure-rate-threshold=70
resilience4j.circuitbreaker.instances.dynamodb-messages.wait-duration-in-open-state=30s
resilience4j.circuitbreaker.instances.dynamodb-messages.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.dynamodb-messages.automatic-transition-from-open-to-half-open-enabled=true

resilience4j.circuitbreaker.instances.dynamodb-stats.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.dynamodb-stats.sliding-window-size=50
resilience4j.circuitbreaker.instances.dynamodb-stats.failure-rate-threshold=70
resilience4j.circuitbreaker.instances.dynamodb-stats.wait-duration-in-open-state=30s
resilience4j.circuitbreaker.instances.dynamodb-stats.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.dynamodb-stats.automatic-transition-from-open-to-half-open-enabled=true

# Retry
app.retry.max-attempts=3
app.retry.backoff-base-ms=100

# Analytics
app.analytics.top-rooms-limit=5
app.analytics.top-users-limit=10

# Write-Behind
app.writebehind.queue-capacity=50000
app.writebehind.batch-size=500
app.writebehind.flush-interval-ms=1000
app.writebehind.db-writer-threads=4
app.writebehind.stats-threads=2
app.writebehind.dlq-capacity=5000
